# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '16.4'

target 'ThisDay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Accessibility'
  pod 'Dispatch'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FSCalendar'
  
  # Pods for ThisDay

end
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            end
        end
    end
end
